
=head1 NAME

nginx-perl - full-featured perl support for nginx

=head1 DESCRIPTION

    - official perl API;
    - connect, read and write ipv4 API;
    - basic resolver functionality;
    - SSL without cached sessions;
    - timer;
    - access handlers;
    - init_worker handlers;
    - configuration-level eval for perl modules;

=head1 INSTALLATION

In this distribution perl module is enabled by default, 
so just F<./configure> should work.

To build with different perl and SSL support use something like:

    % ./configure \
         --with-http_ssl_module \
         --with-perl=/home/you/perl5/perlbrew/perls/perl-5.14.2/bin/perl
    % make

There is a working example in F<hello/>. Should be easy to try things
out:

    % ./objs/nginx-perl -p hello

nginx-perl can be installed alongside nginx, it is safe to do:

    % make isntall

=head1 SEE ALSO

L<http://nginx.net/>, 
L<http://sysoev.ru/nginx/>

=head1 AUTHOR

Alexandr Gomoliako <zzz@zzz.org.ua>

=head1 LICENSE

Copyright 2011 Alexandr Gomoliako. All rights reserved.

This module is free software. It may be used, redistributed and/or modified 
under the same terms as B<nginx> itself.

=cut


